version: '3.5'

services:

  cassandra:
    build: ./cassandra_config
    container_name: cassandra
    restart: on-failure
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
      - "6121:6121"
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    restart: on-failure
    ports:
      - 9100:9100
    # volumes:
    #   - /:/host:ro,rslave
    # command:
    #   - '--path.rootfs=/host'
    depends_on:
     - "cassandra"

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    hostname: cadvisor
    restart: always
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    ports:
        - "8080:8080"
    depends_on:
      - "node-exporter"

  prometheus:
    image: prom/prometheus:v2.19.0
    restart: always
    hostname: prometheus
    container_name: prometheus
    ports:
        - 9090:9090
    volumes:
        - ./prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus_config/rules/node_rules.yml:/etc/prometheus/node_rules.yml
        - ./prometheus_config/rules/container_rules.yml:/etc/prometheus/container_rules.yml
        - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - "cadvisor"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    ports:
        - '9093:9093'
    volumes:
        - ./data/alertmanager:/alertmanager/data
        - ./alertmanager.yml:/alertmanager.yml
    command:
        - "--config.file=/alertmanager.yml"

    depends_on:
      - "prometheus"

  grafana:
    image: grafana/grafana:7.1.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_config/provisioning:/etc/grafana/provisioning
    environment:
      TZ: Asia/Taipei
    depends_on:
     - "alertmanager"